[package]
name = "iso17442-types"
version.workspace = true
authors.workspace = true
description = "ISO 17442 Types"
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
